use classicmodels;
select lastname from employees;
select lastname,firstname,jobTitle from employees;
select * from employees;
select lastname,firstname,jobTitle from employees where jobTitle="Sales Rep";
select lastname,firstname,jobTitle,officecode from employees where jobTitle="Sales Rep" and officecode=1;
select lastname,firstname,jobTitle,officecode from employees where jobTitle="Sales Rep" or officecode=1;
select lastname,firstname,officecode from employees where officecode in(1,2,3);
select lastname,firstname,jobTitle from employees where jobTitle<>"Sales Rep";
select lastname,firstname,officecode from employees where officecode>5;
select lastname,firstname,officecode from employees where officecode<=4;
select customername,country,state from customers where country="USA" and state="CA";
select customername,country,state,creditlimit from customers where country="USA" and state="CA" and creditlimit>100000;
select customername,country from customers where country in ("USA","France");
select customername,country,creditlimit from customers where country in ("USA","France") and creditlimit>100000;
select officeCode,city,phone,country from offices where country in("USA","FRANCE");
select officeCode,city,phone,country from offices where country not in ("USA","FRANCE");
select ordernumber,customerNumber,status,requiredDate from orders where ordernumber in (10165,10287,10310);
select contactLastName,contactFirstName from customers order by contactLastName;
select contactLastName,contactFirstName from customers order by contactLastName desc;
select contactLastName,contactFirstName from customers order by contactLastName desc,contactFirstName;
select customerNumber,customerName,creditlimit from customers order by creditlimit desc limit 5;
select customerNumber,customerName,creditlimit from customers order by creditlimit limit 5;
